<?php

namespace App\Http\Requests\Admin;

use Illuminate\Foundation\Http\FormRequest;

class ConfigSave extends FormRequest
{
    const RULES = [
        // invite & commission
        'invite_force' => '',
        'invite_commission' => 'integer|nullable',
        'invite_gen_limit' => 'integer|nullable',
        'invite_never_expire' => '',
        'commission_first_time_enable' => '',
        'commission_auto_check_enable' => '',
        'commission_withdraw_limit' => 'nullable|numeric',
        'commission_withdraw_method' => 'nullable|array',
        'withdraw_close_enable' => '',
        'commission_distribution_enable' => '',
        'commission_distribution_l1' => 'nullable|numeric',
        'commission_distribution_l2' => 'nullable|numeric',
        'commission_distribution_l3' => 'nullable|numeric',
        // ticket auto-reply
        'ticket_must_wait_reply' => 'boolean',
        'ticket_auto_reply_enable' => 'boolean',
        'ticket_auto_reply_on_user_reply' => 'boolean',
        'ticket_auto_reply_reply_once_per_ticket' => 'boolean',
        'ticket_auto_reply_cooldown_seconds' => 'integer|min:0|max:86400',
        'ticket_auto_reply_max_per_ticket' => 'integer|min:0|max:100',
        'ticket_auto_reply_default_message' => 'nullable|string|max:5000',
        'ticket_auto_reply_rules' => 'nullable|array',
        'ticket_auto_reply_rules.*.enabled' => 'boolean',
        'ticket_auto_reply_rules.*.name' => 'nullable|string|max:100',
        'ticket_auto_reply_rules.*.keyword' => 'nullable|string|max:200',
        'ticket_auto_reply_rules.*.exclude_keyword' => 'nullable|string|max:200',
        'ticket_auto_reply_rules.*.scope' => 'nullable|in:subject,message,both',
        'ticket_auto_reply_rules.*.match_mode' => 'nullable|in:contains,exact,regex',
        'ticket_auto_reply_rules.*.priority' => 'nullable|integer|min:0|max:9999',
        'ticket_auto_reply_rules.*.reply' => 'nullable|string|max:5000',
        // site
        'logo' => 'nullable|url',
        'force_https' => '',
        'stop_register' => '',
        'app_name' => '',
        'app_description' => '',
        'app_url' => 'nullable|url',
        'subscribe_url' => 'nullable',
        'try_out_enable' => '',
        'try_out_plan_id' => 'integer',
        'try_out_hour' => 'numeric',
        'tos_url' => 'nullable|url',
        'currency' => '',
        'currency_symbol' => '',
        // subscribe
        'plan_change_enable' => '',
        'reset_traffic_method' => 'in:0,1,2,3,4',
        'surplus_enable' => '',
        'upgrade_v2_enable' => 'boolean',
        'upgrade_quote_ttl_seconds' => 'integer|min:60|max:86400',
        'upgrade_disable_coupon' => 'boolean',
        'upgrade_disable_user_discount' => 'boolean',
        'upgrade_allow_onetime' => 'boolean',
        'upgrade_min_pay_amount' => 'integer|min:1|max:100000000',
        'upgrade_min_pay_ratio' => 'numeric|min:0|max:1',
        'upgrade_max_credit_cap_ratio' => 'numeric|min:0|max:1',
        'upgrade_credit_coeffs' => 'nullable|array',
        'upgrade_credit_coeffs.monthly' => 'nullable|numeric|min:0|max:1',
        'upgrade_credit_coeffs.quarterly' => 'nullable|numeric|min:0|max:1',
        'upgrade_credit_coeffs.half_yearly' => 'nullable|numeric|min:0|max:1',
        'upgrade_credit_coeffs.yearly' => 'nullable|numeric|min:0|max:1',
        'upgrade_credit_coeffs.two_yearly' => 'nullable|numeric|min:0|max:1',
        'upgrade_credit_coeffs.three_yearly' => 'nullable|numeric|min:0|max:1',
        'upgrade_usage_penalty_rules' => 'nullable|array',
        'upgrade_usage_penalty_rules.*.max_usage_percentage' => 'required|numeric|min:0|max:100',
        'upgrade_usage_penalty_rules.*.coefficient' => 'required|numeric|min:0|max:1',
        'new_order_event_id' => '',
        'renew_order_event_id' => '',
        'change_order_event_id' => '',
        'show_info_to_server_enable' => '',
        'show_protocol_to_server_enable' => '',
        'subscribe_path' => '',
        // server
        'server_token' => 'nullable|min:16',
        'server_pull_interval' => 'integer',
        'server_push_interval' => 'integer',
        'node_realtime_enable' => 'boolean',
        'node_realtime_path' => 'nullable|string|max:100',
        'node_realtime_public_url' => 'nullable|string|max:500',
        'node_realtime_public_port' => 'integer|min:1|max:65535',
        'node_realtime_ping_interval' => 'integer|min:5|max:3600',
        'node_realtime_alert_enable' => 'boolean',
        'node_realtime_alert_notify_telegram' => 'boolean',
        'node_realtime_alert_window_minutes' => 'integer|min:5|max:120',
        'node_realtime_alert_cooldown_minutes' => 'integer|min:1|max:1440',
        'device_limit_mode' => 'in:0,1',
        'node_report_min_traffic' => 'integer|min:0',
        'device_online_min_traffic' => 'integer|min:0',
        'server_api_user_cache_ttl' => 'integer|min:0|max:3600',
        'server_api_config_cache_ttl' => 'integer|min:0|max:3600',
        'server_api_cache_lock_ttl' => 'integer|min:1|max:300',
        'server_api_cache_lock_wait' => 'integer|min:0|max:30',
        'user_sync_retention_days' => 'integer|min:1|max:365',
        'user_sync_delta_limit' => 'integer|min:1|max:100000',
        // frontend
        'frontend_theme' => '',
        'frontend_theme_sidebar' => 'nullable|in:dark,light',
        'frontend_theme_header' => 'nullable|in:dark,light',
        'frontend_theme_color' => 'nullable|in:default,darkblue,black,green',
        'frontend_background_url' => 'nullable|url',
        // email
        'email_template' => '',
        'email_host' => '',
        'email_port' => '',
        'email_username' => '',
        'email_password' => '',
        'email_encryption' => '',
        'email_from_address' => '',
        'remind_mail_enable' => '',
        // telegram
        'telegram_bot_enable' => '',
        'telegram_bot_token' => '',
        'telegram_webhook_url' => 'nullable|url',
        'telegram_discuss_id' => '',
        'telegram_channel_id' => '',
        'telegram_discuss_link' => 'nullable|url',
        // app
        'windows_version' => '',
        'windows_download_url' => '',
        'macos_version' => '',
        'macos_download_url' => '',
        'android_version' => '',
        'android_download_url' => '',
        // safe
        'email_whitelist_enable' => 'boolean',
        'email_whitelist_suffix' => 'nullable|array',
        'email_gmail_limit_enable' => 'boolean',
        'captcha_enable' => 'boolean',
        'captcha_type' => 'in:recaptcha,turnstile,recaptcha-v3',
        'recaptcha_enable' => 'boolean',
        'recaptcha_key' => '',
        'recaptcha_site_key' => '',
        'recaptcha_v3_secret_key' => '',
        'recaptcha_v3_site_key' => '',
        'recaptcha_v3_score_threshold' => 'numeric|min:0|max:1',
        'turnstile_secret_key' => '',
        'turnstile_site_key' => '',
        'email_verify' => 'bool',
        'safe_mode_enable' => 'boolean',
        'register_limit_by_ip_enable' => 'boolean',
        'register_limit_count' => 'integer',
        'register_limit_expire' => 'integer',
        'secure_path' => 'min:8|regex:/^[\w-]*$/',
        'password_limit_enable' => 'boolean',
        'password_limit_count' => 'integer',
        'password_limit_expire' => 'integer',
        'default_remind_expire' => 'boolean',
        'default_remind_traffic' => 'boolean',
        'recharge_bonus_enable' => 'boolean',
        'recharge_bonus_mode' => 'nullable|in:highest,repeat',
        'recharge_bonus_rules' => 'nullable|array',
        'recharge_bonus_rules.*.amount' => 'nullable|numeric|min:0.01|max:1000000',
        'recharge_bonus_rules.*.bonus' => 'nullable|numeric|min:0.01|max:1000000',
        'subscribe_template_singbox' => 'nullable',
        'subscribe_template_clash' => 'nullable',
        'subscribe_template_clashmeta' => 'nullable',
        'subscribe_template_stash' => 'nullable',
        'subscribe_template_surge' => 'nullable',
        'subscribe_template_surfboard' => 'nullable'
    ];
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return self::RULES;
    }

    public function messages()
    {
        // illiteracy prompt
        return [
            'app_url.url' => '站点URL格式不正确，必须携带http(s)://',
            'subscribe_url.url' => '订阅URL格式不正确，必须携带http(s)://',
            'server_token.min' => '通讯密钥长度必须大于16位',
            'tos_url.url' => '服务条款URL格式不正确，必须携带http(s)://',
            'telegram_webhook_url.url' => 'Telegram Webhook地址格式不正确，必须携带http(s)://',
            'telegram_discuss_link.url' => 'Telegram群组地址必须为URL格式，必须携带http(s)://',
            'logo.url' => 'LOGO URL格式不正确，必须携带https(s)://',
            'secure_path.min' => '后台路径长度最小为8位',
            'secure_path.regex' => '后台路径只能为字母或数字',
            'captcha_type.in' => '人机验证类型只能选择 recaptcha、turnstile 或 recaptcha-v3',
            'recaptcha_v3_score_threshold.numeric' => 'reCAPTCHA v3 分数阈值必须为数字',
            'recaptcha_v3_score_threshold.min' => 'reCAPTCHA v3 分数阈值不能小于0',
            'recaptcha_v3_score_threshold.max' => 'reCAPTCHA v3 分数阈值不能大于1',
            'recharge_bonus_mode.in' => '充值赠送模式只能是最高档赠送或按档重复赠送',
            'recharge_bonus_rules.*.amount.numeric' => '充值门槛必须为数字',
            'recharge_bonus_rules.*.amount.min' => '充值门槛必须大于 0',
            'recharge_bonus_rules.*.bonus.numeric' => '赠送金额必须为数字',
            'recharge_bonus_rules.*.bonus.min' => '赠送金额必须大于 0'
        ];
    }
}
